### PR TITLE
[WP] Debian package building with Jenkins

### PR DESCRIPTION
**Pull request by lgcosta**
Initial implementation process in production environment

### CODE REVIEW

**Comment by garnier-quentin** [comment]
Could you add deb package for the new module:
```
libmojolicious-perl
libauthen-simple-perl
```

I don't find a debian package for module: https://metacpan.org/pod/Mojolicious::Plugin::BasicAuthPlus

**Comment by lgcosta** [comment]
Thanks @garnier-quentin 

> 
> I don't find a debian package for module: https://metacpan.org/pod/Mojolicious::Plugin::BasicAuthPlus

I can try to fix it the same way I did here: https://github.com/centreon/centreon-gorgone/blob/57ebeda6c09cbbec83ecfad999ea271266b202e9/ci/scripts/gorgone-deb-package.sh#L21

**Review by lpinsivy — APPROVED** [review]

**Review by garnier-quentin — DISMISSED** [review]

**Comment by garnier-quentin** [comment]
Have you finished your PR ?

**Comment by lgcosta** [comment]
> Have you finished your PR ? Seems there is a conflict to solve.

conflict resolved. Necessary to make/run jobs in Jenkins. @lpinsivy and/or @zguennoune02 help me ?

**Pull request closed without merging**
